### ISSUE TITLE
Doesn't work on latest master branch (0.15.0-dev.1092+d772c0627)

### ISSUE THREAD

**Issue by HaraldWik** [castholm/zigglgen#27]
```sh
/home/admin/.cache/zig/p/sdl3-0.0.1-NmT1QxmtHgClb-lMOw-Pstc7gRpMHC8cPXk8TYsBuPYe/build.zig:10:10: error: no field named 'target' in struct 'Build.TestOptions'
        .target = target,
         ^~~~~~
/home/admin/.zig/lib/std/Build.zig:778:25: note: struct declared here
pub const TestOptions = struct {
                        ^~~~~~
referenced by:
    runBuild__anon_77915: /home/admin/.zig/lib/std/Build.zig:2137:44
    dependencyInner__anon_73188: /home/admin/.zig/lib/std/Build.zig:2117:29
    9 reference(s) hidden; use '-freference-trace=11' to see all references
/home/admin/.cache/zig/p/zigglgen-0.4.0-bmyqLX_gLQDFXilQ5VQ9fJeOHKU1RFrggOzRqTGBX79W/build.zig:28:10: error: no field named 'root_source_file' in struct 'Build.TestOptions'
        .root_source_file = generate_everything: {
         ^~~~~~~~~~~~~~~~
/home/admin/.zig/lib/std/Build.zig:778:25: note: struct declared here
pub const TestOptions = struct {
                        ^~~~~~
```

**Comment by castholm** [comment]
0b8261eb00f098ea65e2a1b0a42798a2d1410ccb
